# Generated by Django 5.2.7 on 2025-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', through='students.Enrollment', to='courses.course'),
        ),
    ]
