# Generated by Django 5.2.7 on 2025-10-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_duration_remove_course_price_and_more'),
        ('students', '0002_alter_students_enrolled_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_students', to='courses.course'),
        ),
    ]
