# Generated by Django 5.2.7 on 2025-10-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
