# Generated by Django 5.2.7 on 2025-10-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
